name: Deploy to Firebase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "firebase-deploy"
  cancel-in-progress: false

jobs:
  # Build and Deploy job
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        working-directory: ai-portfolio
        run: |
          echo "Installing dependencies with npm install"
          npm install

      - name: Build
        working-directory: ai-portfolio
        run: npm run build
        env:
          NEXT_PUBLIC_SITE_URL: https://vikyath.me

      - name: Setup Firebase CLI
        run: npm install -g firebase-tools

      - name: Create Firebase Service Account Key
        run: echo "$FIREBASE_SERVICE_ACCOUNT" > /tmp/firebase-service-account.json
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Deploy to Firebase
        working-directory: ai-portfolio
        run: firebase deploy --only hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/firebase-service-account.json
